version: "3.8"

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      MONGO_URI: mongodb://mongo:27017/

  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/frontend

volumes:
  mongo-data: